FROM python:3.12.0-slim

# Set working directory
WORKDIR /code

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend code and tests
COPY ./app ./app
COPY ./test ./test
COPY ./pytest.ini ./pytest.ini

# Set PYTHONPATH so 'app' is discoverable
ENV PYTHONPATH=/code

# Default command to run tests
CMD ["python", "-m", "pytest", "test/", "-v", "--tb=short"]
